version: '2.1'

volumes:
  sense-data:
  dashboard-data:

services: 
  gps:
    privileged: true
    build: "./gps"
    devices: 
      - "/dev/ttyACM0:/dev/ttyACM0"
      # Provide UART0 for gpsd to fall back to.
      - "/dev/ttyAMA0:/dev/ttyAMA0"
      # Allows gpsd.py to detect the current RPi version
      - "/proc/device-tree/model:/proc/device-tree/model"
    environment:
      - "DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket"
    ports:
      - "2947"
    labels:
      io.resin.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.balena-api: '1'
  co2:
    privileged: true
    build: "./co2"
    network_mode: host  
    depends_on:
      - gps
    expose:
      - "2947"
      - "7575"
    labels:
      io.resin.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1' 
  wifi-connect:
        build: ./wifi-connect
        network_mode: "host"
        privileged: true
        labels:
            io.balena.features.dbus: '1'
            io.balena.features.firmware: "1"
        cap_add:
            - NET_ADMIN
        environment:
            DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
